<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Confluent.Kafka" Version="13.2.2" />
    <PackageReference Include="Aspire.Microsoft.EntityFrameworkCore.SqlServer" Version="13.2.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.6" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.6" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\KafkaWorkflow.DataAccess\KafkaWorkflow.DataAccess.csproj" />
    <ProjectReference Include="..\KafkaWorkflow.ServiceDefaults\KafkaWorkflow.ServiceDefaults.csproj" />
  </ItemGroup>

</Project>
